  on:
    push:
      branches:
        - master





  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: "Login to Docker hub"
          run: docker login --username ${{ secrets.DOCKER_USERN }} --password ${{ secrets.DOCKER_TOKEN }}

        - name: "Building docker image"
          run: docker build -t ${{ secrets.DOCKER_USERN }}/nun .

        - name: "pushing"
          run: docker push ${{ secrets.DOCKER_USERN }}/nun
